/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifprbiopark.queijo_desktop.view;

import br.com.ifprbiopark.queijo_desktop.control.ControlePessoa;
import br.com.ifprbiopark.queijo_desktop.inicializacao.QueijoDesktop;
import br.com.ifprbiopark.queijo_desktop.model.Pessoa;
import com.google.common.base.Strings;
import java.awt.Color;
import java.awt.Dimension;
import java.text.ParseException;
import javax.swing.JOptionPane;

public class TelaPessoaView extends javax.swing.JInternalFrame {

    Pessoa pessoa = new Pessoa();

    /**
     * Creates new form FormFornecedor
     */
    public TelaPessoaView() throws ParseException {
        initComponents();
        
        //mascara situacao fiscal (documento)        
        alteraMascara();
        try{
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        }
        catch (Exception ex){
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.red);
        }        
    }
    
    public void setId(int id){
        txtID.setText(String.valueOf(id));
        consultar();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtEndereco = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbTipoDoc = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtDoc = new javax.swing.JFormattedTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Pessoa");
        setName("Cadastro de Pessoa"); // NOI18N

        txtNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        txtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEnderecoKeyPressed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produtor", "Fornecedor", "Funcionário", "Cliente" }));
        cmbTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Pessoa"));

        cmbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "CNPJ" }));
        cmbTipoDoc.setBorder(javax.swing.BorderFactory.createTitledBorder("Documento"));
        cmbTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDocActionPerformed(evt);
            }
        });

        txtID.setEditable(false);
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));

        txtTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        txtDoc.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF/CNPJ"));
        txtDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDocKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(594, 614, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDoc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEndereco)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alteraMascara(){
        try{
            txtDoc.setText("");
            if (cmbTipoDoc.getSelectedItem()== "CPF"){
                    txtDoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));

            }
            else if (cmbTipoDoc.getSelectedItem() == "CNPJ"){
                    txtDoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/####-##")));
            }            
        }
        catch (Exception ex){
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.red);
        }
    }
    
    private void salvar(){
        try {
            boolean salvamentoLiberado = true;
            if (Strings.isNullOrEmpty(txtNome.getText())){
                salvamentoLiberado = false;
                txtNome.setBackground(Color.pink);
            }            
            if ( Strings.isNullOrEmpty(txtDoc.getText())||txtDoc.getText().equals("   .   .   -  ") || txtDoc.getText().equals("   .   .   /    -  ")){
                salvamentoLiberado = false;
                txtDoc.setBackground(Color.pink);
            }
            if (Strings.isNullOrEmpty(txtEndereco.getText())){
                salvamentoLiberado = false;
                txtEndereco.setBackground(Color.pink);
            }
            
            if (salvamentoLiberado){
                pessoa.setNome(txtNome.getText());
                pessoa.setEndereco(txtEndereco.getText());
                pessoa.setCadastro(txtDoc.getText());
                pessoa.setTelefone(txtTelefone.getText());

                if (cmbTipoDoc.getSelectedItem().equals("CPF")){
                    pessoa.setTipoFiscal("0");
                }
                else if (cmbTipoDoc.getSelectedItem().equals("CNPJ")){
                    pessoa.setTipoFiscal("1");
                }            

                pessoa.setTipoPessoa((String)cmbTipo.getSelectedItem());

                ControlePessoa controle = new ControlePessoa();
                controle.salvar(pessoa);

                QueijoDesktop.telaPrincipal.setMenssagem("Salvo com sucesso.", Color.GREEN);

                txtID.setText(String.valueOf(pessoa.getIdPessoa()));
            }
            else{
                QueijoDesktop.telaPrincipal.setMenssagem("Por favor, preencha os campos", Color.yellow);
            }                  
        } catch (Exception ex) {
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.red);
        }
    }
    
    private void consultar(){
        try{
            Pessoa p = new Pessoa();
            ControlePessoa cp = new ControlePessoa();
            if (!Strings.isNullOrEmpty(txtID.getText())){            

                p = cp.consultar(Integer.parseInt(txtID.getText()));
            }
            
            if (!Strings.isNullOrEmpty(p.getNome())){
                txtNome.setText(p.getNome());
                txtEndereco.setText(p.getEndereco());
                
                if (p.getTipoFiscal().equals("0")){
                    cmbTipoDoc.setSelectedIndex(0);
                }
                else if (p.getTipoFiscal().equals("1")){
                    cmbTipoDoc.setSelectedIndex(1);
                }
                
                txtDoc.setText(p.getCadastro());
                
                txtTelefone.setText(p.getTelefone());
                
                cmbTipo.setSelectedItem(p.getTipoPessoa());
            }
            
            btnSalvar.setText("Atualizar");            
        }
        catch (Exception ex){
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.red);
        }        
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (!Strings.isNullOrEmpty(txtNome.getText()) || !Strings.isNullOrEmpty(txtEndereco.getText())){
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair sem salvar?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                this.dispose();
            }
        }
        else{
            this.dispose();;
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocKeyPressed
        txtDoc.setBackground(Color.white);
    }//GEN-LAST:event_txtDocKeyPressed

    private void txtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnderecoKeyPressed
        txtEndereco.setBackground(Color.white);
    }//GEN-LAST:event_txtEnderecoKeyPressed

    private void cmbTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDocActionPerformed
        alteraMascara();
    }//GEN-LAST:event_cmbTipoDocActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        txtNome.setBackground(Color.white);
    }//GEN-LAST:event_txtNomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> cmbTipoDoc;
    private javax.swing.JFormattedTextField txtDoc;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
