/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifprbiopark.queijo_desktop.view;

import br.com.ifprbiopark.queijo_desktop.model.FabricacaoQueijo;
import java.awt.Dimension;
import java.util.HashSet;

/**
 *
 * @author marcos.andre
 */
public class TelaFabricacaoQueijo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaProcessamentoView
     */
    
    
    public TelaFabricacaoQueijo() {
        initComponents();
       
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tfLote = new javax.swing.JTextField();
        cbQuantidadeLeite = new javax.swing.JTextField();
        jcColeta = new javax.swing.JComboBox<>();
        jcTipoQueijo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtTemperaturaPross = new javax.swing.JTextField();
        rbLeiteCru = new javax.swing.JRadioButton();
        rbLeitePast = new javax.swing.JRadioButton();
        txtTempoPross = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtTempPreMat = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtQuantFerm = new javax.swing.JTextField();
        txtMarcaFerm = new javax.swing.JTextField();
        txtItemFerm = new javax.swing.JTextField();
        txtTempoFerm = new javax.swing.JTextField();
        txtPhPreMat = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtCloretoCalcio = new javax.swing.JTextField();
        txtPhEsformagem = new javax.swing.JTextField();
        txtTempoCoagulacao = new javax.swing.JTextField();
        txtCoagulante = new javax.swing.JTextField();
        txtPhCorte = new javax.swing.JTextField();
        txtPh24 = new javax.swing.JTextField();
        txtDessoragem = new javax.swing.JTextField();
        txtTemperatura24 = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtTemperaturaSalga = new javax.swing.JTextField();
        txtDataSalga = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        txtTipoTratamento = new javax.swing.JTextField();
        txtDataCasca = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        txtPecasQueijo = new javax.swing.JTextField();
        txtPesoMedio = new javax.swing.JTextField();
        txtPesoTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacao = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        cmbFuncionario = new javax.swing.JComboBox<>();
        txtLotePAcabado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTempoTratamento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Processamento");
        setMinimumSize(new java.awt.Dimension(976, 694));
        setPreferredSize(new java.awt.Dimension(976, 694));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Processamento"));

        tfLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote:"));

        cbQuantidadeLeite.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtde Utilizada:"));
        cbQuantidadeLeite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuantidadeLeiteActionPerformed(evt);
            }
        });

        jcColeta.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrega de Leite"));

        jcTipoQueijo.setBorder(javax.swing.BorderFactory.createTitledBorder("Receita de Queijo"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jcTipoQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfLote, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbQuantidadeLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfLote)
                .addComponent(cbQuantidadeLeite))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipoQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Processamento"));

        txtTemperaturaPross.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperaturaPross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaProssActionPerformed(evt);
            }
        });

        rbLeiteCru.setBackground(new java.awt.Color(255, 255, 255));
        rbLeiteCru.setText("Leite Cru");

        rbLeitePast.setBackground(new java.awt.Color(255, 255, 255));
        rbLeitePast.setText("Leite Pasteuzidado");

        txtTempoPross.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo:"));
        txtTempoPross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoProssActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbLeiteCru)
                    .addComponent(rbLeitePast))
                .addGap(44, 44, 44)
                .addComponent(txtTempoPross, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTemperaturaPross, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbLeiteCru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbLeitePast))
                    .addComponent(txtTempoPross)
                    .addComponent(txtTemperaturaPross))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pré Maturação"));

        txtTempPreMat.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTempPreMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempPreMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(txtTempPreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtTempPreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fermento"));

        txtQuantFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade:"));
        txtQuantFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantFermActionPerformed(evt);
            }
        });

        txtMarcaFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca:"));
        txtMarcaFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaFermActionPerformed(evt);
            }
        });

        txtItemFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Item:"));
        txtItemFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemFermActionPerformed(evt);
            }
        });

        txtTempoFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo:"));
        txtTempoFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoFermActionPerformed(evt);
            }
        });

        txtPhPreMat.setBorder(javax.swing.BorderFactory.createTitledBorder("PH após Pré Maturação:"));
        txtPhPreMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhPreMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtQuantFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTempoFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtItemFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMarcaFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPhPreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantFerm, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(txtTempoFerm)
                            .addComponent(txtItemFerm)))
                    .addComponent(txtPhPreMat)
                    .addComponent(txtMarcaFerm))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Coagulação"));

        txtCloretoCalcio.setBorder(javax.swing.BorderFactory.createTitledBorder("Cloreto de Cálcio (ml)"));
        txtCloretoCalcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCloretoCalcioActionPerformed(evt);
            }
        });

        txtPhEsformagem.setBorder(javax.swing.BorderFactory.createTitledBorder("pH da Esformagem:"));
        txtPhEsformagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhEsformagemActionPerformed(evt);
            }
        });

        txtTempoCoagulacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de Coagulação"));
        txtTempoCoagulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoCoagulacaoActionPerformed(evt);
            }
        });

        txtCoagulante.setBorder(javax.swing.BorderFactory.createTitledBorder("Coagulante"));
        txtCoagulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCoagulanteActionPerformed(evt);
            }
        });

        txtPhCorte.setBorder(javax.swing.BorderFactory.createTitledBorder("pH do Corte:"));
        txtPhCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhCorteActionPerformed(evt);
            }
        });

        txtPh24.setBorder(javax.swing.BorderFactory.createTitledBorder("pH após 24Hs"));
        txtPh24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPh24ActionPerformed(evt);
            }
        });

        txtDessoragem.setBorder(javax.swing.BorderFactory.createTitledBorder("Dessoragem:"));
        txtDessoragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDessoragemActionPerformed(evt);
            }
        });

        txtTemperatura24.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperatura24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatura24ActionPerformed(evt);
            }
        });

        txtTemperatura.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCloretoCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtPh24, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDessoragem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCoagulante, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTempoCoagulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhEsformagem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTemperatura24, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCloretoCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoagulante, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempoCoagulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhEsformagem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPh24, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtDessoragem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTemperatura24)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Maturação"));

        txtTemperaturaSalga.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperaturaSalga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaSalgaActionPerformed(evt);
            }
        });

        txtDataSalga.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        txtDataSalga.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDataSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemperaturaSalga, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txtTemperaturaSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtDataSalga)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamento da Casca"));

        txtTipoTratamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de tratamento:"));
        txtTipoTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoTratamentoActionPerformed(evt);
            }
        });

        txtDataCasca.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Inicial"));
        txtDataCasca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCascaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txtDataCasca, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTipoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTipoTratamento, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(txtDataCasca)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendimento"));

        txtPecasQueijo.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtd de Peças Produzidas:"));
        txtPecasQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPecasQueijoActionPerformed(evt);
            }
        });

        txtPesoMedio.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso Médio:"));
        txtPesoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoMedioActionPerformed(evt);
            }
        });

        txtPesoTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso Total:"));
        txtPesoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtPecasQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txtPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPecasQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações:"));
        jScrollPane1.setViewportView(txtObservacao);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        cmbFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionario"));

        txtLotePAcabado.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote (Produto Acabado):"));
        txtLotePAcabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLotePAcabadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLotePAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLotePAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de Salga");

        txtTempoTratamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de tratamento:"));
        txtTempoTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoTratamentoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTempoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTempoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnExcluir))
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperaturaProssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaProssActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaProssActionPerformed

    private void txtQuantFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantFermActionPerformed

    private void txtTempPreMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempPreMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempPreMatActionPerformed

    private void txtTempoProssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoProssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoProssActionPerformed

    private void txtMarcaFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaFermActionPerformed

    private void txtItemFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemFermActionPerformed

    private void txtTempoFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoFermActionPerformed

    private void txtPhPreMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhPreMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhPreMatActionPerformed

    private void txtCloretoCalcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCloretoCalcioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCloretoCalcioActionPerformed

    private void txtTemperaturaSalgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaSalgaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaSalgaActionPerformed

    private void txtPhEsformagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhEsformagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhEsformagemActionPerformed

    private void txtTempoCoagulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoCoagulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoCoagulacaoActionPerformed

    private void txtCoagulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCoagulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCoagulanteActionPerformed

    private void txtPhCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhCorteActionPerformed

    private void txtPh24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPh24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPh24ActionPerformed

    private void txtDessoragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDessoragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDessoragemActionPerformed

    private void txtTemperatura24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatura24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatura24ActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void txtTempoTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoTratamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoTratamentoActionPerformed

    private void txtLotePAcabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLotePAcabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLotePAcabadoActionPerformed

    private void txtPecasQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPecasQueijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPecasQueijoActionPerformed

    private void txtPesoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoMedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoMedioActionPerformed

    private void txtPesoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoTotalActionPerformed

    private void txtTipoTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoTratamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoTratamentoActionPerformed

    private void cbQuantidadeLeiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuantidadeLeiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQuantidadeLeiteActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtDataCascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCascaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCascaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        FabricacaoQueijo queijo = new FabricacaoQueijo();
//        
//        queijo.setTipoQueijo_idTipoQueijo(jcTipoQueijo.getSelectedIndex());
//        queijo.setColetaLeite_idColetaLeite(jcColeta.getSelectedIndex());
//        queijo.setTipoQueijo_idTipoQueijo(tipoQueijo_idTipoQueijo);
//        queijo.setDataFabricacao(dataFabricacao);
//        queijo.setLoteQueijo(loteQueijo);
//        queijo.setColetaLeite_idColetaLeite(coletaLeite_idColetaLeite);
//        queijo.setProcessamento_idProcessamento(processamento_idProcessamento);
//        queijo.setTempoProcessamento(tempoProcessamento);
//        queijo.setTemperaturaProcessamento(temperaturaProcessamento);
//        queijo.setTemperaturaPreMaturacao(temperaturaPreMaturacao);
//        queijo.setFermento_idFermento(fermento_idFermento);
//        queijo.setQtdFermento(0);
//        queijo.setTempoMaturacao(tempoMaturacao);
//        queijo.setPhMaturacao(0);
//        queijo.setTemperaturaCoagulacao(temperaturaCoagulacao);
//        queijo.setQtdClCalcio(0);
//        queijo.setQtdCoagulante(0);
//        queijo.setTempoCoagulacao(tempoCoagulacao);
//        queijo.setPhCorte(0);
//        queijo.setPhEnformagem(0);
//        queijo.setPhFinal(0);
//        queijo.setDessoragem(dessoragem);
//        queijo.setTemperaturaDessoragem(temperaturaDessoragem);
//        queijo.setTipoSalga(tipoSalga);
//        queijo.setDataMaturacao(dataMaturacao);
//        queijo.setTempoMaturacao(temperaturaMaturacao);
//        queijo.setDataLavagem(dataLavagem);
//        queijo.setTipoTratamento(tipoTratamento);
//        queijo.setTempoTratamento(tempoTratamento);
//        queijo.setQtdPecas(qtdPecas);
//        queijo.setPesoMPecas(pesoMPecas);
//        queijo.setPesoTotal(pesoTotal);
//        queijo.setObservacoes(observacoes);
//        queijo.setFabricacaoQueijocol(fabricacaoQueijocol);
//        queijo.setResponsavel_idResponsavel(Responsavel_idResponsavel);
//        
//        
//        private Pessoa Responsavel_idResponsavel;

//                jcTipoQueijo
//                tfLote
//                jcColeta
//                cbQuantidadeLeite
//                rbLeiteCru
//                rbLeitePast
//                txtTempoPross
//                txtTemperaturaPross
//                txtTempPreMat
//                txtQuantFerm
//                txtTempoFerm
//                txtItemFerm
//                txtMarcaFerm
//                txtPhPreMat
//                txtTemperatura
//                txtCloretoCalcio
//                txtCoagulante
//                txtTempoCoagulacao
//                txtPhCorte
//                txtPhEsformagem
//                txtPh24
//                txtDessoragem
//                txtTemperatura24
//                txtDataSalga
//                txtTemperaturaSalga
//                txtTempoTratamento
//                txtDataCasca
//                txtTipoTratamento
//                txtPecasQueijo
//                txtPesoTotal
//                txtPesoMedio
//                txtLotePAcabado
//                cmbFuncionario
//                txtObservacao
    
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cbQuantidadeLeite;
    private javax.swing.JComboBox<String> cmbFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcColeta;
    private javax.swing.JComboBox<String> jcTipoQueijo;
    private javax.swing.JRadioButton rbLeiteCru;
    private javax.swing.JRadioButton rbLeitePast;
    private javax.swing.JTextField tfLote;
    private javax.swing.JTextField txtCloretoCalcio;
    private javax.swing.JTextField txtCoagulante;
    private javax.swing.JFormattedTextField txtDataCasca;
    private javax.swing.JFormattedTextField txtDataSalga;
    private javax.swing.JTextField txtDessoragem;
    private javax.swing.JTextField txtItemFerm;
    private javax.swing.JTextField txtLotePAcabado;
    private javax.swing.JTextField txtMarcaFerm;
    private javax.swing.JTextPane txtObservacao;
    private javax.swing.JTextField txtPecasQueijo;
    private javax.swing.JTextField txtPesoMedio;
    private javax.swing.JTextField txtPesoTotal;
    private javax.swing.JTextField txtPh24;
    private javax.swing.JTextField txtPhCorte;
    private javax.swing.JTextField txtPhEsformagem;
    private javax.swing.JTextField txtPhPreMat;
    private javax.swing.JTextField txtQuantFerm;
    private javax.swing.JTextField txtTempPreMat;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtTemperatura24;
    private javax.swing.JTextField txtTemperaturaPross;
    private javax.swing.JTextField txtTemperaturaSalga;
    private javax.swing.JTextField txtTempoCoagulacao;
    private javax.swing.JTextField txtTempoFerm;
    private javax.swing.JTextField txtTempoPross;
    private javax.swing.JTextField txtTempoTratamento;
    private javax.swing.JTextField txtTipoTratamento;
    // End of variables declaration//GEN-END:variables
}
