/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifprbiopark.queijo_desktop.view;

import br.com.ifprbiopark.queijo_desktop.control.ControleColetaLeite;
import br.com.ifprbiopark.queijo_desktop.control.ControlePessoa;
import br.com.ifprbiopark.queijo_desktop.control.ControleReceitaQueijo;
import br.com.ifprbiopark.queijo_desktop.exception.db.DbException;
import br.com.ifprbiopark.queijo_desktop.model.ColetaLeite;
import br.com.ifprbiopark.queijo_desktop.model.FabricacaoQueijo;
import br.com.ifprbiopark.queijo_desktop.model.Pessoa;
import br.com.ifprbiopark.queijo_desktop.model.ReceitaQueijo;
import com.google.common.base.Strings;
import java.awt.Dimension;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcos.andre
 */
public class TelaFabricacaoQueijo extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaProcessamentoView
     */
    //lista de receitas do queijo
    ControleReceitaQueijo rqControl;
    List<ReceitaQueijo> listaReceitaQueijo;

    //lista de coletas de leite;
    ControleColetaLeite cleite;
    List<ColetaLeite> listaColetaLeite;
    
    //lista de funcionarios
    ControlePessoa cPessoa;
    List<Pessoa> listaFuncionarios;
    
    
    public TelaFabricacaoQueijo() {
        initComponents();

        //carregar as receitas
        rqControl = new ControleReceitaQueijo();
        try {
            listaReceitaQueijo = rqControl.listaReceitaQueijo();
            //jcTipoQueijo.removeAll();
            jcTipoQueijo.addItem("");
            for (ReceitaQueijo receitaQueijo : listaReceitaQueijo) {
                jcTipoQueijo.addItem(receitaQueijo.getNomeTipo());
            }

        } catch (DbException ex) {
            Logger.getLogger(TelaFabricacaoQueijo.class.getName()).log(Level.SEVERE, null, ex);
        }

        //carregar as coletas de leite
        cleite = new ControleColetaLeite();

        try {
            listaColetaLeite = cleite.listaColeta();
            //jcColeta.removeAll();
            jcColeta.addItem("");
            for (ColetaLeite coletaLeite : listaColetaLeite) {
                jcColeta.addItem(coletaLeite.getLoteColeta());
            }

        } catch (DbException ex) {
            Logger.getLogger(TelaFabricacaoQueijo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //carregar os funcionarios
        cPessoa = new ControlePessoa();
        try {
            listaFuncionarios = cPessoa.listaFuncionarios();
            //cmbFuncionario.removeAll();
            cmbFuncionario.addItem("");
            for (Pessoa pessoas : listaFuncionarios) {                
                cmbFuncionario.addItem(pessoas.getNome());
            }
          
        } catch (DbException ex) {
            Logger.getLogger(TelaFabricacaoQueijo.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtLote = new javax.swing.JTextField();
        txtQuantidadeLeiteUtilizada = new javax.swing.JTextField();
        jcColeta = new javax.swing.JComboBox<>();
        jcTipoQueijo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtTemperaturaPross = new javax.swing.JTextField();
        txtTempoFermento = new javax.swing.JTextField();
        jcTipoLeite = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtTempPreMat = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtQuantFerm = new javax.swing.JTextField();
        txtMarcaFerm = new javax.swing.JTextField();
        txtTipoFermento = new javax.swing.JTextField();
        txtTempoFermentacao = new javax.swing.JTextField();
        txtPhPreMatura = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtCloretoCalcio = new javax.swing.JTextField();
        txtPhEsformagem = new javax.swing.JTextField();
        txtTempoCoagulacao = new javax.swing.JTextField();
        txtQtdCoagulante = new javax.swing.JTextField();
        txtPhCorte = new javax.swing.JTextField();
        txtPh24 = new javax.swing.JTextField();
        txtDessoragem = new javax.swing.JTextField();
        txtTemperatura24 = new javax.swing.JTextField();
        txtTemperaturaCoagula = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtTemperaturaSalga = new javax.swing.JTextField();
        txtDataSalga = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        tfTipoTratamentoCasca = new javax.swing.JTextField();
        tfDataTratamentoCasca = new javax.swing.JFormattedTextField();
        jPanel8 = new javax.swing.JPanel();
        tfQueijoProduzido = new javax.swing.JTextField();
        tfPesoMedioLote = new javax.swing.JTextField();
        tfPesoTotalLote = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfObservacao = new javax.swing.JTextPane();
        jPanel9 = new javax.swing.JPanel();
        cmbFuncionario = new javax.swing.JComboBox<>();
        tfLoteProdutoAcabado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTempoTratamento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JToggleButton();
        btnExcluir = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Processamento");
        setMinimumSize(new java.awt.Dimension(976, 694));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Processamento"));

        txtLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote:"));

        txtQuantidadeLeiteUtilizada.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtde Utilizada:"));
        txtQuantidadeLeiteUtilizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeLeiteUtilizadaActionPerformed(evt);
            }
        });

        jcColeta.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrega de Leite"));

        jcTipoQueijo.setBorder(javax.swing.BorderFactory.createTitledBorder("Receita de Queijo"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jcTipoQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtQuantidadeLeiteUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtLote)
                .addComponent(txtQuantidadeLeiteUtilizada))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcColeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipoQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Processamento"));

        txtTemperaturaPross.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperaturaPross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaProssActionPerformed(evt);
            }
        });

        txtTempoFermento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo:"));
        txtTempoFermento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoFermentoActionPerformed(evt);
            }
        });

        jcTipoLeite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cru", "Pasteurizado" }));
        jcTipoLeite.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Leite"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jcTipoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTempoFermento, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTemperaturaPross, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jcTipoLeite)
                    .addComponent(txtTempoFermento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTemperaturaPross, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pré Maturação"));

        txtTempPreMat.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTempPreMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempPreMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(txtTempPreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtTempPreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fermento"));

        txtQuantFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade:"));
        txtQuantFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantFermActionPerformed(evt);
            }
        });

        txtMarcaFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca:"));
        txtMarcaFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaFermActionPerformed(evt);
            }
        });

        txtTipoFermento.setBorder(javax.swing.BorderFactory.createTitledBorder("Item(Tipo de Fermento)"));
        txtTipoFermento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoFermentoActionPerformed(evt);
            }
        });

        txtTempoFermentacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo:"));
        txtTempoFermentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoFermentacaoActionPerformed(evt);
            }
        });

        txtPhPreMatura.setBorder(javax.swing.BorderFactory.createTitledBorder("PH após Pré Maturação:"));
        txtPhPreMatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhPreMaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtQuantFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTempoFermentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTipoFermento, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMarcaFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPhPreMatura, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuantFerm, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(txtTempoFermentacao)
                            .addComponent(txtTipoFermento)))
                    .addComponent(txtPhPreMatura)
                    .addComponent(txtMarcaFerm))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Coagulação"));

        txtCloretoCalcio.setBorder(javax.swing.BorderFactory.createTitledBorder("Cloreto de Cálcio (ml)"));
        txtCloretoCalcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCloretoCalcioActionPerformed(evt);
            }
        });

        txtPhEsformagem.setBorder(javax.swing.BorderFactory.createTitledBorder("pH da Esformagem:"));
        txtPhEsformagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhEsformagemActionPerformed(evt);
            }
        });

        txtTempoCoagulacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de Coagulação"));
        txtTempoCoagulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoCoagulacaoActionPerformed(evt);
            }
        });

        txtQtdCoagulante.setBorder(javax.swing.BorderFactory.createTitledBorder("Coagulante"));
        txtQtdCoagulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdCoagulanteActionPerformed(evt);
            }
        });

        txtPhCorte.setBorder(javax.swing.BorderFactory.createTitledBorder("pH do Corte:"));
        txtPhCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhCorteActionPerformed(evt);
            }
        });

        txtPh24.setBorder(javax.swing.BorderFactory.createTitledBorder("pH após 24Hs"));
        txtPh24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPh24ActionPerformed(evt);
            }
        });

        txtDessoragem.setBorder(javax.swing.BorderFactory.createTitledBorder("Dessoragem:"));
        txtDessoragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDessoragemActionPerformed(evt);
            }
        });

        txtTemperatura24.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperatura24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatura24ActionPerformed(evt);
            }
        });

        txtTemperaturaCoagula.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperaturaCoagula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaCoagulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTemperaturaCoagula, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCloretoCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtPh24, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDessoragem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtQtdCoagulante, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTempoCoagulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhEsformagem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTemperatura24, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperaturaCoagula, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCloretoCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtdCoagulante, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempoCoagulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhEsformagem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPh24)
                    .addComponent(txtDessoragem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTemperatura24)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Maturação"));

        txtTemperaturaSalga.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura:"));
        txtTemperaturaSalga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaSalgaActionPerformed(evt);
            }
        });

        txtDataSalga.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        txtDataSalga.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDataSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemperaturaSalga, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txtTemperaturaSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(txtDataSalga)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamento da Casca"));

        tfTipoTratamentoCasca.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de tratamento:"));
        tfTipoTratamentoCasca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoTratamentoCascaActionPerformed(evt);
            }
        });

        tfDataTratamentoCasca.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Inicial"));
        tfDataTratamentoCasca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataTratamentoCascaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(tfDataTratamentoCasca, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfTipoTratamentoCasca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfTipoTratamentoCasca, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(tfDataTratamentoCasca)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendimento"));

        tfQueijoProduzido.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtd de Peças Produzidas:"));
        tfQueijoProduzido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQueijoProduzidoActionPerformed(evt);
            }
        });

        tfPesoMedioLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso Médio:"));
        tfPesoMedioLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoMedioLoteActionPerformed(evt);
            }
        });

        tfPesoTotalLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso Total:"));
        tfPesoTotalLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoTotalLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(tfQueijoProduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(tfPesoTotalLote, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesoMedioLote, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQueijoProduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPesoMedioLote, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPesoTotalLote, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações:"));
        jScrollPane1.setViewportView(tfObservacao);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        cmbFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionario"));

        tfLoteProdutoAcabado.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote (Produto Acabado):"));
        tfLoteProdutoAcabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoteProdutoAcabadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfLoteProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLoteProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tipo de Salga");

        txtTempoTratamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de tratamento:"));
        txtTempoTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoTratamentoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTempoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTempoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnExcluir))
                        .addGap(52, 52, 52))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperaturaProssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaProssActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaProssActionPerformed

    private void txtQuantFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantFermActionPerformed

    private void txtTempPreMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempPreMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempPreMatActionPerformed

    private void txtTempoFermentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoFermentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoFermentoActionPerformed

    private void txtMarcaFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaFermActionPerformed

    private void txtTipoFermentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoFermentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoFermentoActionPerformed

    private void txtTempoFermentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoFermentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoFermentacaoActionPerformed

    private void txtPhPreMaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhPreMaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhPreMaturaActionPerformed

    private void txtCloretoCalcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCloretoCalcioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCloretoCalcioActionPerformed

    private void txtTemperaturaSalgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaSalgaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaSalgaActionPerformed

    private void txtPhEsformagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhEsformagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhEsformagemActionPerformed

    private void txtTempoCoagulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoCoagulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoCoagulacaoActionPerformed

    private void txtQtdCoagulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdCoagulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdCoagulanteActionPerformed

    private void txtPhCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhCorteActionPerformed

    private void txtPh24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPh24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPh24ActionPerformed

    private void txtDessoragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDessoragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDessoragemActionPerformed

    private void txtTemperatura24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatura24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatura24ActionPerformed

    private void txtTemperaturaCoagulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaCoagulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaCoagulaActionPerformed

    private void txtTempoTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoTratamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoTratamentoActionPerformed

    private void tfLoteProdutoAcabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoteProdutoAcabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoteProdutoAcabadoActionPerformed

    private void tfQueijoProduzidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQueijoProduzidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQueijoProduzidoActionPerformed

    private void tfPesoMedioLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoMedioLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoMedioLoteActionPerformed

    private void tfPesoTotalLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoTotalLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoTotalLoteActionPerformed

    private void tfTipoTratamentoCascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoTratamentoCascaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipoTratamentoCascaActionPerformed

    private void txtQuantidadeLeiteUtilizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeLeiteUtilizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeLeiteUtilizadaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tfDataTratamentoCascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataTratamentoCascaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataTratamentoCascaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        FabricacaoQueijo queijo = new FabricacaoQueijo();

        //informacoes iniciais de processamento        
        queijo.setTipoQueijo_idTipoQueijo(listaReceitaQueijo.get(jcTipoQueijo.getSelectedIndex()));
        queijo.setLoteQueijo(txtLote.getText());
        queijo.setColetaLeite_idColetaLeite((listaColetaLeite.get(jcColeta.getSelectedIndex())));
        queijo.setQtdLeiteUtilizada(Double.parseDouble(txtQuantidadeLeiteUtilizada.getText()));

        //Processamento
        queijo.setTipoLeite((String) jcTipoLeite.getSelectedItem());
        queijo.setTempoProcessamento(parseInteiro(txtTempoFermento.getText()));
        queijo.setTemperaturaProcessamento(parseInteiro(txtTemperaturaPross.getText()));

        //Prematuracao
        queijo.setTemperaturaPreMaturacao(parseInteiro(txtTempPreMat.getText()));

        //Insercao de Fermento
        queijo.setQtdFermento(parseDoubles(txtQuantFerm.getText()));
        queijo.setTempoFermentacao(parseInteiro(txtTempoFermento.getText()));
        queijo.setFermento(txtTipoFermento.getText());
        queijo.setMarcaFermento(txtMarcaFerm.getText());
        queijo.setPhPreMaturacao(parseInteiro(txtPhPreMatura.getText()));

        //Coagulacao
        queijo.setTemperaturaCoagulacao(parseInteiro(txtTemperaturaCoagula.getText()));
        queijo.setQtdClCalcio(parseDoubles(txtCloretoCalcio.getText()));
        queijo.setQtdCoagulante(parseDoubles(txtQtdCoagulante.getText()));
        queijo.setTempoCoagulacao(parseInteiro(txtTempoCoagulacao.getText()));
        queijo.setPhCorte(parseDoubles(txtPhCorte.getText()));
        queijo.setPhEnformagem(parseDoubles(txtPhEsformagem.getText()));
        queijo.setPh24(parseInteiro(txtPh24.getText()));
        queijo.setDessoragem(parseInteiro(txtDessoragem.getText()));
        queijo.setTemperaturaDessoragem(parseInteiro(txtTemperatura24.getText()));

        //Etapa de Salga
        queijo.setDataSalga(txtDataSalga.getText());
        queijo.setTemperaturaSalga(txtTemperaturaSalga.getText());
        queijo.setTempoTratamentoSalga(txtTempoTratamento.getText());

        //tratamento casca
        queijo.setDataTratamentoCasca(tfDataTratamentoCasca.getText());
        queijo.setTipoTratamentoCasca(tfTipoTratamentoCasca.getText());

        //Rendimento
        queijo.setQtdPecas(parseInteiro(tfQueijoProduzido.getText()));
        queijo.setPesoTotal(parseDoubles(tfPesoTotalLote.getText()));
        queijo.setPesoMedioPecas(parseDoubles(tfPesoMedioLote.getText()));
        queijo.setLoteAcabado(tfLoteProdutoAcabado.getText());
        queijo.setResponsavel_idResponsavel(listaFuncionarios.get(cmbFuncionario.getSelectedIndex()));
        queijo.setObservacoes(tfObservacao.getText());


    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnExcluir;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcColeta;
    private javax.swing.JComboBox<String> jcTipoLeite;
    private javax.swing.JComboBox<String> jcTipoQueijo;
    private javax.swing.JFormattedTextField tfDataTratamentoCasca;
    private javax.swing.JTextField tfLoteProdutoAcabado;
    private javax.swing.JTextPane tfObservacao;
    private javax.swing.JTextField tfPesoMedioLote;
    private javax.swing.JTextField tfPesoTotalLote;
    private javax.swing.JTextField tfQueijoProduzido;
    private javax.swing.JTextField tfTipoTratamentoCasca;
    private javax.swing.JTextField txtCloretoCalcio;
    private javax.swing.JFormattedTextField txtDataSalga;
    private javax.swing.JTextField txtDessoragem;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtMarcaFerm;
    private javax.swing.JTextField txtPh24;
    private javax.swing.JTextField txtPhCorte;
    private javax.swing.JTextField txtPhEsformagem;
    private javax.swing.JTextField txtPhPreMatura;
    private javax.swing.JTextField txtQtdCoagulante;
    private javax.swing.JTextField txtQuantFerm;
    private javax.swing.JTextField txtQuantidadeLeiteUtilizada;
    private javax.swing.JTextField txtTempPreMat;
    private javax.swing.JTextField txtTemperatura24;
    private javax.swing.JTextField txtTemperaturaCoagula;
    private javax.swing.JTextField txtTemperaturaPross;
    private javax.swing.JTextField txtTemperaturaSalga;
    private javax.swing.JTextField txtTempoCoagulacao;
    private javax.swing.JTextField txtTempoFermentacao;
    private javax.swing.JTextField txtTempoFermento;
    private javax.swing.JTextField txtTempoTratamento;
    private javax.swing.JTextField txtTipoFermento;
    // End of variables declaration//GEN-END:variables

    private Integer parseInteiro(String value) {

        if (Strings.isNullOrEmpty(value)) {
            return null;
        }
        return Integer.parseInt(value);
    }
    
    private Double parseDoubles(String value) {

        if (Strings.isNullOrEmpty(value)) {
            return null;
        }
        return Double.parseDouble(value);
    }
}
