package br.com.ifprbiopark.queijo_desktop.view;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRootPane;

public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalView() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDesktop = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuPessoa = new javax.swing.JMenuItem();
        menuEntradaLeite = new javax.swing.JMenuItem();
        menuClassificacaoLeite = new javax.swing.JMenuItem();
        menuProcessamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        painelDesktop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout painelDesktopLayout = new javax.swing.GroupLayout(painelDesktop);
        painelDesktop.setLayout(painelDesktopLayout);
        painelDesktopLayout.setHorizontalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        painelDesktopLayout.setVerticalGroup(
            painelDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        menuCadastro.setText("Cadastro");

        menuPessoa.setText("Pessoa");
        menuPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuPessoa);

        menuEntradaLeite.setText("Entrada de Leite");
        menuEntradaLeite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEntradaLeiteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuEntradaLeite);

        menuClassificacaoLeite.setText("Classificação de Leite");
        menuClassificacaoLeite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClassificacaoLeiteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuClassificacaoLeite);

        menuProcessamento.setText("Processamento");
        menuProcessamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcessamentoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuProcessamento);

        jMenuBar1.add(menuCadastro);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(painelDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(painelDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoaActionPerformed
        try {
            TelaPessoaView formPessoa = new TelaPessoaView();
            painelDesktop.add(formPessoa);
            formPessoa.setMaximum(true);
            formPessoa.setVisible(true);
            formPessoa.setPosicao();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPessoaActionPerformed

    private void menuEntradaLeiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEntradaLeiteActionPerformed
        try {
            TelaColetaLeiteView formEntradaLeite = new TelaColetaLeiteView();
            painelDesktop.add(formEntradaLeite);
            formEntradaLeite.setMaximum(true);
            formEntradaLeite.setVisible(true);        
            formEntradaLeite.setPosicao();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuEntradaLeiteActionPerformed

    private void menuClassificacaoLeiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClassificacaoLeiteActionPerformed
        try {
            TelaClassificacaoLeiteView formClassificacaoLeite = new TelaClassificacaoLeiteView();
            painelDesktop.add(formClassificacaoLeite);
            formClassificacaoLeite.setMaximum(true);
            formClassificacaoLeite.setVisible(true);
            formClassificacaoLeite.setPosicao();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        
    }//GEN-LAST:event_menuClassificacaoLeiteActionPerformed

    private void menuProcessamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcessamentoActionPerformed
        try {
            TelaProcessamentoView formProcessamentoe = new TelaProcessamentoView();
            painelDesktop.add(formProcessamentoe);
            formProcessamentoe.setMaximum(true);
            formProcessamentoe.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            formProcessamentoe.setVisible(true);
            formProcessamentoe.setPosicao();
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaPrincipalView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_menuProcessamentoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuClassificacaoLeite;
    private javax.swing.JMenuItem menuEntradaLeite;
    private javax.swing.JMenuItem menuPessoa;
    private javax.swing.JMenuItem menuProcessamento;
    private javax.swing.JDesktopPane painelDesktop;
    // End of variables declaration//GEN-END:variables
}
