/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifprbiopark.queijo_desktop.view;

import br.com.ifprbiopark.queijo_desktop.control.ControleColetaLeite;
import br.com.ifprbiopark.queijo_desktop.control.ControleFabricacaoQueijo;
import br.com.ifprbiopark.queijo_desktop.control.ControleReceitaQueijo;
import br.com.ifprbiopark.queijo_desktop.inicializacao.QueijoDesktop;
import br.com.ifprbiopark.queijo_desktop.model.ColetaLeite;
import br.com.ifprbiopark.queijo_desktop.model.FabricacaoQueijo;
import br.com.ifprbiopark.queijo_desktop.model.ReceitaQueijo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author jhona
 */
public class TelaNovaFabricacaoView extends javax.swing.JInternalFrame {
    
    //controles
    private ControleReceitaQueijo rqControl = new ControleReceitaQueijo();
    private ControleColetaLeite cleite = new ControleColetaLeite();
    private ControleFabricacaoQueijo cfq = new ControleFabricacaoQueijo();
    
    //listas
    private List<ReceitaQueijo> listaReceitaQueijo;
    private List<ColetaLeite> listaColetaLeite;
    
    //formato de data
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private DefaultFormatterFactory formatoDeDataCampo;
    
    //variáveis de controle
    private Date hoje = new Date();
    private boolean virgulaQtd = false;
    private String qtd = "";

    /**
     * Creates new form TalaNovaFabricacaoView
     */
    public TelaNovaFabricacaoView() {
        initComponents();
        
        setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iconeQueijos.png")));
        
        try {
            formatoDeDataCampo = new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####"));
            txtData.setFormatterFactory(formatoDeDataCampo);
            alteraData();
        } catch (Exception ex) {
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.RED);
        }
        
        try {
            listaReceitaQueijo = rqControl.listaReceitaQueijo();
            //jcTipoQueijo.removeAll();
            cmbReceita.addItem("");
            for (ReceitaQueijo receitaQueijo : listaReceitaQueijo) {
                cmbReceita.addItem(receitaQueijo.getNomeTipo());
            }

        } catch (Exception ex) {
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.RED);
        }
        
        //carregar as coletas de leite
        try {
            listaColetaLeite = cleite.listaColeta();
            //jcColeta.removeAll();
            cmbLoteLeite.addItem("");
            for (ColetaLeite coletaLeite : listaColetaLeite) {
                cmbLoteLeite.addItem(coletaLeite.getLoteColeta());
            }

        } catch (Exception ex) {
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.RED);
        }
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCriar = new javax.swing.JButton();
        txtCancelar = new javax.swing.JButton();
        cmbReceita = new javax.swing.JComboBox<>();
        txtLote = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        cmbLoteLeite = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JFormattedTextField();
        chkDataAuto = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Nova fabricação");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnCriar.setText("Criar");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        txtCancelar.setText("Cancelar");
        txtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelarActionPerformed(evt);
            }
        });

        cmbReceita.setBorder(javax.swing.BorderFactory.createTitledBorder("Receita de queijo:"));

        txtLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote:"));

        txtQtd.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtde utilizada (L):"));
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdKeyTyped(evt);
            }
        });

        cmbLoteLeite.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote da coleta de leite:"));

        txtData.setEditable(false);
        txtData.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));

        chkDataAuto.setBackground(new java.awt.Color(255, 255, 255));
        chkDataAuto.setSelected(true);
        chkDataAuto.setText("Data automática");
        chkDataAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkDataAutoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDataAuto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbReceita, 0, 276, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbLoteLeite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQtd)
                            .addComponent(txtLote, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(cmbLoteLeite, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDataAuto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(txtCancelar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        criar();
    }//GEN-LAST:event_btnCriarActionPerformed

    private void txtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelarActionPerformed
        fechar();
    }//GEN-LAST:event_txtCancelarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        fechar();
    }//GEN-LAST:event_formInternalFrameClosing

    private void chkDataAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkDataAutoMouseClicked
        alteraData();
    }//GEN-LAST:event_chkDataAutoMouseClicked

    private void txtQtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyTyped
        vericaTeclaDouble(evt);
    }//GEN-LAST:event_txtQtdKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JCheckBox chkDataAuto;
    private javax.swing.JComboBox<String> cmbLoteLeite;
    private javax.swing.JComboBox<String> cmbReceita;
    private javax.swing.JButton txtCancelar;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables

    private void criar() {
        try{
            FabricacaoQueijo fq = new FabricacaoQueijo();
            fq.setLoteQueijo(txtLote.getText());
            fq.setReceitaQueijo(listaReceitaQueijo.get(cmbReceita.getSelectedIndex() - 1));
            fq.setColetaLeite(listaColetaLeite.get(cmbLoteLeite.getSelectedIndex() - 1));
            fq.setQtdLeite(Double.parseDouble(txtQtd.getText().replace(',', '.')));
        
            
            if (chkDataAuto.isSelected()){
                String now = sdf.format(new Date());
                fq.setDataFabricacao(sdf.parse(now));
            }                
            else{
                fq.setDataFabricacao(sdf.parse(txtData.getText()));
            }
            
            fq.setInativo(0);
            
            cfq.salvar(fq);
            abrirFabricacao(fq);
            
        }
        catch (Exception ex){
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.red);
        }       
    }
    
    private void abrirFabricacao(FabricacaoQueijo fq){
        try {
            TelaFabricacaoQueijoView form = new TelaFabricacaoQueijoView();
            form.setFabricacao(fq);
            QueijoDesktop.telaPrincipal.getPainelDesktop().add(form);
            form.setPosicao();
            form.setVisible(true);       
            this.dispose();
        } catch (Exception ex) {
            QueijoDesktop.telaPrincipal.setMenssagem("Erro: " + ex.getMessage(), Color.red);
        }
    }
    
    private void fechar(){
        try{
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        }
        catch (Exception ex){
            QueijoDesktop.telaPrincipal.setMenssagem("Erro ao fechar: " + ex.getMessage(), Color.red);
        }
        
    }

    private void alteraData() {
        if (chkDataAuto.isSelected()){
            txtData.setEditable(false);
            txtData.setText(sdf.format(hoje));
        }
        else{
            txtData.setEditable(true);
            txtData.setText(null);
        }
    }
    
    private void vericaTeclaDouble(KeyEvent e) {
        char c = e.getKeyChar();
        JTextField campo = (JTextField)e.getSource();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && ( c != ',') ) {
            e.consume();
        }

        if ( c == ','){
            for (char ch : campo.getText().toCharArray()){
                if (c == ch){
                    e.consume();
                    break;
                }
            }
        }            
    }
}
