/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifprbiopark.queijo_desktop.view;

import br.com.ifprbiopark.queijo_desktop.control.ControleColetaLeite;
import br.com.ifprbiopark.queijo_desktop.control.ControleFabricacaoQueijo;
import br.com.ifprbiopark.queijo_desktop.control.ControlePessoa;
import br.com.ifprbiopark.queijo_desktop.control.ControleReceitaQueijo;
import br.com.ifprbiopark.queijo_desktop.exception.FabricacaoException;
import br.com.ifprbiopark.queijo_desktop.exception.db.DbException;
import br.com.ifprbiopark.queijo_desktop.model.ColetaLeite;
import br.com.ifprbiopark.queijo_desktop.model.FabricacaoQueijo;
import br.com.ifprbiopark.queijo_desktop.model.Pessoa;
import br.com.ifprbiopark.queijo_desktop.model.ReceitaQueijo;
import com.google.common.base.Strings;
import java.awt.Dimension;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author marcos.andre
 */
public class TelaFabricacaoQueijoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaProcessamentoView
     */
    //lista de receitas do queijo
    ControleReceitaQueijo rqControl;
    List<ReceitaQueijo> listaReceitaQueijo;

    //lista de coletas de leite;
    ControleColetaLeite cleite;
    List<ColetaLeite> listaColetaLeite;

    //lista de funcionarios
    ControlePessoa cPessoa;
    List<Pessoa> listaFuncionarios;
    FabricacaoQueijo fq = new FabricacaoQueijo();
    ControleFabricacaoQueijo cfq = new ControleFabricacaoQueijo();

    public TelaFabricacaoQueijoView() {
        initComponents();

        //carregar as receitas
        rqControl = new ControleReceitaQueijo();
//        try {
//            listaReceitaQueijo = rqControl.listaReceitaQueijo();
//            //jcTipoQueijo.removeAll();
//            jcTipoQueijo.addItem("");
//            for (ReceitaQueijo receitaQueijo : listaReceitaQueijo) {
//                jcTipoQueijo.addItem(receitaQueijo.getNomeTipo());
//            }
//
//        } catch (DbException ex) {
//            Logger.getLogger(TelaFabricacaoQueijoView.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        //carregar as coletas de leite
//        cleite = new ControleColetaLeite();
//
//        try {
//            listaColetaLeite = cleite.listaColeta();
//            //jcColeta.removeAll();
//            jcColeta.addItem("");
//            for (ColetaLeite coletaLeite : listaColetaLeite) {
//                jcColeta.addItem(coletaLeite.getLoteColeta());
//            }
//
//        } catch (DbException ex) {
//            Logger.getLogger(TelaFabricacaoQueijoView.class.getName()).log(Level.SEVERE, null, ex);
//        }

        //carregar os funcionarios
        cPessoa = new ControlePessoa();
        try {
            listaFuncionarios = cPessoa.listaFuncionarios();
            //cmbFuncionario.removeAll();
            cmbFuncionario.addItem("");
            for (Pessoa pessoas : listaFuncionarios) {
                cmbFuncionario.addItem(pessoas.getNome());
            }

        } catch (DbException ex) {
            Logger.getLogger(TelaFabricacaoQueijoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setID(int id){
        txtID.setText(String.valueOf(id));
        consultar();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlInfo = new javax.swing.JPanel();
        txtLote = new javax.swing.JTextField();
        txtQuantidadeLeiteUtilizada = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtReceitaQueijo = new javax.swing.JTextField();
        txtLoteEntraga = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JToggleButton();
        btnCancelar = new javax.swing.JToggleButton();
        guia = new javax.swing.JTabbedPane();
        pnlProcessamento = new javax.swing.JPanel();
        txtTemperaturaPross = new javax.swing.JTextField();
        txtTempoFermento = new javax.swing.JTextField();
        jcTipoLeite = new javax.swing.JComboBox<>();
        pnlPreMaturacao = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtMarcaFerm = new javax.swing.JTextField();
        txtTipoFermento = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        txtQuantFerm = new javax.swing.JTextField();
        txtTempoFermentacao = new javax.swing.JTextField();
        txtTempPreMat = new javax.swing.JTextField();
        txtPhPreMatura = new javax.swing.JTextField();
        pnlCoagulacao = new javax.swing.JPanel();
        txtTemperaturaCoagula = new javax.swing.JTextField();
        txtQtdCoagulante = new javax.swing.JTextField();
        txtTempoCoagulacao = new javax.swing.JTextField();
        txtPhCorte = new javax.swing.JTextField();
        txtPhEsformagem = new javax.swing.JTextField();
        txtPh24 = new javax.swing.JTextField();
        txtCloretoCalcio = new javax.swing.JTextField();
        txtDessoragem = new javax.swing.JTextField();
        txtTemperatura24 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        pnlMaturacao = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tfTipoTratamentoCasca = new javax.swing.JTextField();
        tfDataTratamentoCasca = new javax.swing.JFormattedTextField();
        txtTempoTratamento = new javax.swing.JTextField();
        txtTemperaturaSalga = new javax.swing.JTextField();
        txtDataSalga = new javax.swing.JFormattedTextField();
        pnlRendimento = new javax.swing.JPanel();
        tfPesoMedioLote = new javax.swing.JTextField();
        tfPesoTotalLote = new javax.swing.JTextField();
        tfQueijoProduzido = new javax.swing.JTextField();
        pnlObsevacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfObservacao = new javax.swing.JTextPane();
        pnlFinalizacao = new javax.swing.JPanel();
        cmbFuncionario = new javax.swing.JComboBox<>();
        tfLoteProdutoAcabado = new javax.swing.JTextField();
        chkAtivo = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fabricação");
        setMinimumSize(new java.awt.Dimension(976, 694));
        setRequestFocusEnabled(false);

        pnlInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da fabricação"));

        txtLote.setEditable(false);
        txtLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote:"));

        txtQuantidadeLeiteUtilizada.setEditable(false);
        txtQuantidadeLeiteUtilizada.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtde Utilizada (L):"));
        txtQuantidadeLeiteUtilizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeLeiteUtilizadaActionPerformed(evt);
            }
        });

        txtID.setEditable(false);
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder("ID:"));

        txtReceitaQueijo.setEditable(false);
        txtReceitaQueijo.setBorder(javax.swing.BorderFactory.createTitledBorder("Receita de queijo"));

        txtLoteEntraga.setEditable(false);
        txtLoteEntraga.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote da entrega de leite:"));

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReceitaQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoteEntraga, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeLeiteUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReceitaQueijo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoteEntraga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeLeiteUtilizada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlProcessamento.setBackground(new java.awt.Color(255, 255, 255));
        pnlProcessamento.setForeground(new java.awt.Color(255, 255, 255));

        txtTemperaturaPross.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura (°C):"));
        txtTemperaturaPross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaProssActionPerformed(evt);
            }
        });

        txtTempoFermento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo (min):"));
        txtTempoFermento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoFermentoActionPerformed(evt);
            }
        });

        jcTipoLeite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cru", "Pasteurizado" }));
        jcTipoLeite.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Leite"));
        jcTipoLeite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoLeiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProcessamentoLayout = new javax.swing.GroupLayout(pnlProcessamento);
        pnlProcessamento.setLayout(pnlProcessamentoLayout);
        pnlProcessamentoLayout.setHorizontalGroup(
            pnlProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcTipoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTempoFermento, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTemperaturaPross, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(517, Short.MAX_VALUE))
        );
        pnlProcessamentoLayout.setVerticalGroup(
            pnlProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProcessamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProcessamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcTipoLeite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempoFermento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaPross, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195))
        );

        guia.addTab("Processamento", pnlProcessamento);

        pnlPreMaturacao.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fermento"));

        txtMarcaFerm.setEditable(false);
        txtMarcaFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Marca:"));
        txtMarcaFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaFermActionPerformed(evt);
            }
        });

        txtTipoFermento.setEditable(false);
        txtTipoFermento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Fermento:"));
        txtTipoFermento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoFermentoActionPerformed(evt);
            }
        });

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        txtQuantFerm.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade (g):"));
        txtQuantFerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantFermActionPerformed(evt);
            }
        });

        txtTempoFermentacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo(min):"));
        txtTempoFermentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoFermentacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoFermento, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarcaFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantFerm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTempoFermentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuantFerm)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTipoFermento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtMarcaFerm)
            .addComponent(txtTempoFermentacao)
        );

        txtTempPreMat.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura utilizada(°C):"));
        txtTempPreMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempPreMatActionPerformed(evt);
            }
        });

        txtPhPreMatura.setBorder(javax.swing.BorderFactory.createTitledBorder("pH após pré-maturação:"));
        txtPhPreMatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhPreMaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPreMaturacaoLayout = new javax.swing.GroupLayout(pnlPreMaturacao);
        pnlPreMaturacao.setLayout(pnlPreMaturacaoLayout);
        pnlPreMaturacaoLayout.setHorizontalGroup(
            pnlPreMaturacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreMaturacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPreMaturacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhPreMatura, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempPreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlPreMaturacaoLayout.setVerticalGroup(
            pnlPreMaturacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPreMaturacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTempPreMat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhPreMatura)
                .addGap(46, 46, 46))
        );

        guia.addTab("Pré-maturação", pnlPreMaturacao);

        pnlCoagulacao.setBackground(new java.awt.Color(255, 255, 255));

        txtTemperaturaCoagula.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura (°C):"));
        txtTemperaturaCoagula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaCoagulaActionPerformed(evt);
            }
        });

        txtQtdCoagulante.setBorder(javax.swing.BorderFactory.createTitledBorder("Coagulante (mL):"));
        txtQtdCoagulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdCoagulanteActionPerformed(evt);
            }
        });

        txtTempoCoagulacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de coagulação (min):"));
        txtTempoCoagulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoCoagulacaoActionPerformed(evt);
            }
        });

        txtPhCorte.setBorder(javax.swing.BorderFactory.createTitledBorder("pH do corte:"));
        txtPhCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhCorteActionPerformed(evt);
            }
        });

        txtPhEsformagem.setBorder(javax.swing.BorderFactory.createTitledBorder("pH da enformagem:"));
        txtPhEsformagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhEsformagemActionPerformed(evt);
            }
        });

        txtPh24.setBorder(javax.swing.BorderFactory.createTitledBorder("pH após 24Hs:"));
        txtPh24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPh24ActionPerformed(evt);
            }
        });

        txtCloretoCalcio.setBorder(javax.swing.BorderFactory.createTitledBorder("Cloreto de Cálcio (ml):"));
        txtCloretoCalcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCloretoCalcioActionPerformed(evt);
            }
        });

        txtDessoragem.setBorder(javax.swing.BorderFactory.createTitledBorder("Dessoragem:"));
        txtDessoragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDessoragemActionPerformed(evt);
            }
        });

        txtTemperatura24.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura dessoragem (°C):"));
        txtTemperatura24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperatura24ActionPerformed(evt);
            }
        });

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de salga:"));

        javax.swing.GroupLayout pnlCoagulacaoLayout = new javax.swing.GroupLayout(pnlCoagulacao);
        pnlCoagulacao.setLayout(pnlCoagulacaoLayout);
        pnlCoagulacaoLayout.setHorizontalGroup(
            pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoagulacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQtdCoagulante, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtTemperaturaCoagula)
                    .addComponent(txtPhCorte)
                    .addComponent(txtDessoragem))
                .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoagulacaoLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(txtCloretoCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlCoagulacaoLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(txtTempoCoagulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoagulacaoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTemperatura24, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(txtPhEsformagem))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPh24)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        pnlCoagulacaoLayout.setVerticalGroup(
            pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCoagulacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTemperaturaCoagula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCloretoCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdCoagulante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempoCoagulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhEsformagem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPh24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCoagulacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTemperatura24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDessoragem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        guia.addTab("Coagulação", pnlCoagulacao);

        pnlMaturacao.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamento da Casca"));

        tfTipoTratamentoCasca.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de tratamento:"));
        tfTipoTratamentoCasca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTipoTratamentoCascaActionPerformed(evt);
            }
        });

        tfDataTratamentoCasca.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de lavagem:"));
        tfDataTratamentoCasca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataTratamentoCascaActionPerformed(evt);
            }
        });

        txtTempoTratamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de tratamento (min):"));
        txtTempoTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempoTratamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(tfDataTratamentoCasca, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTipoTratamentoCasca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTempoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 291, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataTratamentoCasca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTipoTratamentoCasca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempoTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        txtTemperaturaSalga.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura (°C):"));
        txtTemperaturaSalga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaSalgaActionPerformed(evt);
            }
        });

        txtDataSalga.setBorder(javax.swing.BorderFactory.createTitledBorder("Data:"));
        txtDataSalga.setToolTipText("");

        javax.swing.GroupLayout pnlMaturacaoLayout = new javax.swing.GroupLayout(pnlMaturacao);
        pnlMaturacao.setLayout(pnlMaturacaoLayout);
        pnlMaturacaoLayout.setHorizontalGroup(
            pnlMaturacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaturacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaturacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaturacaoLayout.createSequentialGroup()
                        .addComponent(txtDataSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTemperaturaSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMaturacaoLayout.setVerticalGroup(
            pnlMaturacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaturacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMaturacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperaturaSalga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        guia.addTab("Maturação", pnlMaturacao);

        pnlRendimento.setBackground(new java.awt.Color(255, 255, 255));

        tfPesoMedioLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso médio (Kg):"));
        tfPesoMedioLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoMedioLoteActionPerformed(evt);
            }
        });

        tfPesoTotalLote.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso total (Kg):"));
        tfPesoTotalLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesoTotalLoteActionPerformed(evt);
            }
        });

        tfQueijoProduzido.setBorder(javax.swing.BorderFactory.createTitledBorder("Qtd de peças produzidas:"));
        tfQueijoProduzido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQueijoProduzidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRendimentoLayout = new javax.swing.GroupLayout(pnlRendimento);
        pnlRendimento.setLayout(pnlRendimentoLayout);
        pnlRendimentoLayout.setHorizontalGroup(
            pnlRendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPesoTotalLote, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(tfQueijoProduzido)
                    .addComponent(tfPesoMedioLote))
                .addContainerGap(781, Short.MAX_VALUE))
        );
        pnlRendimentoLayout.setVerticalGroup(
            pnlRendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRendimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfQueijoProduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesoMedioLote, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesoTotalLote, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        guia.addTab("Rendimento", pnlRendimento);

        pnlObsevacao.setBackground(new java.awt.Color(255, 255, 255));

        tfObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações:"));
        jScrollPane1.setViewportView(tfObservacao);

        javax.swing.GroupLayout pnlObsevacaoLayout = new javax.swing.GroupLayout(pnlObsevacao);
        pnlObsevacao.setLayout(pnlObsevacaoLayout);
        pnlObsevacaoLayout.setHorizontalGroup(
            pnlObsevacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
        );
        pnlObsevacaoLayout.setVerticalGroup(
            pnlObsevacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );

        guia.addTab("Observações", pnlObsevacao);

        pnlFinalizacao.setBackground(new java.awt.Color(255, 255, 255));

        cmbFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionario"));

        tfLoteProdutoAcabado.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote (Produto Acabado):"));
        tfLoteProdutoAcabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoteProdutoAcabadoActionPerformed(evt);
            }
        });

        chkAtivo.setBackground(new java.awt.Color(255, 255, 255));
        chkAtivo.setSelected(true);
        chkAtivo.setText("Fabricação ativa");

        javax.swing.GroupLayout pnlFinalizacaoLayout = new javax.swing.GroupLayout(pnlFinalizacao);
        pnlFinalizacao.setLayout(pnlFinalizacaoLayout);
        pnlFinalizacaoLayout.setHorizontalGroup(
            pnlFinalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFinalizacaoLayout.createSequentialGroup()
                        .addComponent(tfLoteProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkAtivo))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        pnlFinalizacaoLayout.setVerticalGroup(
            pnlFinalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalizacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFinalizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLoteProdutoAcabado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAtivo)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        guia.addTab("Finalização", pnlFinalizacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guia))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guia, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        guia.getAccessibleContext().setAccessibleName("Processamento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemperaturaProssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaProssActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaProssActionPerformed

    private void txtQuantFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantFermActionPerformed

    private void txtTempPreMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempPreMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempPreMatActionPerformed

    private void txtTempoFermentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoFermentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoFermentoActionPerformed

    private void txtMarcaFermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaFermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaFermActionPerformed

    private void txtTipoFermentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoFermentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoFermentoActionPerformed

    private void txtTempoFermentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoFermentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoFermentacaoActionPerformed

    private void txtPhPreMaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhPreMaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhPreMaturaActionPerformed

    private void txtCloretoCalcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCloretoCalcioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCloretoCalcioActionPerformed

    private void txtTemperaturaSalgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaSalgaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaSalgaActionPerformed

    private void txtPhEsformagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhEsformagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhEsformagemActionPerformed

    private void txtTempoCoagulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoCoagulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoCoagulacaoActionPerformed

    private void txtQtdCoagulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdCoagulanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdCoagulanteActionPerformed

    private void txtPhCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhCorteActionPerformed

    private void txtPh24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPh24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPh24ActionPerformed

    private void txtDessoragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDessoragemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDessoragemActionPerformed

    private void txtTemperatura24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperatura24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperatura24ActionPerformed

    private void txtTemperaturaCoagulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaCoagulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaCoagulaActionPerformed

    private void txtTempoTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempoTratamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempoTratamentoActionPerformed

    private void tfLoteProdutoAcabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoteProdutoAcabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoteProdutoAcabadoActionPerformed

    private void tfQueijoProduzidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQueijoProduzidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQueijoProduzidoActionPerformed

    private void tfPesoMedioLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoMedioLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoMedioLoteActionPerformed

    private void tfPesoTotalLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesoTotalLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesoTotalLoteActionPerformed

    private void tfTipoTratamentoCascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTipoTratamentoCascaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipoTratamentoCascaActionPerformed

    private void txtQuantidadeLeiteUtilizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeLeiteUtilizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeLeiteUtilizadaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfDataTratamentoCascaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataTratamentoCascaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataTratamentoCascaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            FabricacaoQueijo queijo = new FabricacaoQueijo();
            ControleFabricacaoQueijo cQueijo = new ControleFabricacaoQueijo();

            //informacoes iniciais de processamento
            queijo.setReceitaQueijo(listaReceitaQueijo.get(fq.getReceitaQueijo().getIdTipoQueijo()));
            queijo.setLoteQueijo(txtLote.getText());
            queijo.setColetaLeite((listaColetaLeite.get(fq.getColetaLeite().getIdColetaLeite())));
            queijo.setQtdLeite(parseDoubles(txtQuantidadeLeiteUtilizada.getText()));

            //Processamento
            queijo.setTipoLeite((String) jcTipoLeite.getSelectedItem());
            queijo.setTempoProcessamento(parseInteiro(txtTempoFermento.getText()));
            queijo.setTemperaturaProcessamento(parseInteiro(txtTemperaturaPross.getText()));

            //Prematuracao
            queijo.setTemperaturaPreMaturacao(parseInteiro(txtTempPreMat.getText()));

            //Insercao de Fermento
            //fermento_id
            queijo.setQtdFermento(parseDoubles(txtQuantFerm.getText()));
            queijo.setTempoFermentacao(parseInteiro(txtTempoFermento.getText()));
            //queijo.setFermento(txtTipoFermento.getText());
            //queijo.setMarcaFermento(txtMarcaFerm.getText());
            queijo.setPhPreMaturacao(parseInteiro(txtPhPreMatura.getText()));

            //Coagulacao
            queijo.setTemperaturaCoagulacao(parseInteiro(txtTemperaturaCoagula.getText()));
            queijo.setQtdClCalcio(parseDoubles(txtCloretoCalcio.getText()));
            queijo.setQtdCoagulante(parseDoubles(txtQtdCoagulante.getText()));
            queijo.setTempoCoagulacao(parseInteiro(txtTempoCoagulacao.getText()));
            queijo.setPhCorte(parseDoubles(txtPhCorte.getText()));
            queijo.setPhEnformagem(parseDoubles(txtPhEsformagem.getText()));
            //queijo.setPhMaturacao(parseDoubles(txtPhPreMatura.getText()));
            queijo.setDessoragem(parseInteiro(txtDessoragem.getText()));
            queijo.setTemperaturaDessoragem(parseInteiro(txtTemperatura24.getText()));

            //Etapa de Salga
            //queijo.setDataSalga(txtDataSalga.getText());
            //queijo.setTemperaturaSalga(txtTemperaturaSalga.getText());
            //queijo.setTempoTratamentoSalga(txtTempoTratamento.getText());

            //tratamento casca
            //queijo.setDataTratamentoCasca(tfDataTratamentoCasca.getText());
            //queijo.setTipoTratamentoCasca(tfTipoTratamentoCasca.getText());

            //Rendimento
            queijo.setQtdPecas(parseInteiro(tfQueijoProduzido.getText()));
            queijo.setPesoTotal(parseDoubles(tfPesoTotalLote.getText()));
            queijo.setPesoMedioPecas(parseDoubles(tfPesoMedioLote.getText()));
            queijo.setLoteAcabado(tfLoteProdutoAcabado.getText());
            queijo.setResponsavel(listaFuncionarios.get(cmbFuncionario.getSelectedIndex()));
            queijo.setObservacoes(tfObservacao.getText());

            cQueijo.salvar(queijo);
        } catch (FabricacaoException ex) {
            Logger.getLogger(TelaFabricacaoQueijoView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jcTipoLeiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoLeiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTipoLeiteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JComboBox<String> cmbFuncionario;
    private javax.swing.JTabbedPane guia;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> jcTipoLeite;
    private javax.swing.JPanel pnlCoagulacao;
    private javax.swing.JPanel pnlFinalizacao;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlMaturacao;
    private javax.swing.JPanel pnlObsevacao;
    private javax.swing.JPanel pnlPreMaturacao;
    private javax.swing.JPanel pnlProcessamento;
    private javax.swing.JPanel pnlRendimento;
    private javax.swing.JFormattedTextField tfDataTratamentoCasca;
    private javax.swing.JTextField tfLoteProdutoAcabado;
    private javax.swing.JTextPane tfObservacao;
    private javax.swing.JTextField tfPesoMedioLote;
    private javax.swing.JTextField tfPesoTotalLote;
    private javax.swing.JTextField tfQueijoProduzido;
    private javax.swing.JTextField tfTipoTratamentoCasca;
    private javax.swing.JTextField txtCloretoCalcio;
    private javax.swing.JFormattedTextField txtDataSalga;
    private javax.swing.JTextField txtDessoragem;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtLoteEntraga;
    private javax.swing.JTextField txtMarcaFerm;
    private javax.swing.JTextField txtPh24;
    private javax.swing.JTextField txtPhCorte;
    private javax.swing.JTextField txtPhEsformagem;
    private javax.swing.JTextField txtPhPreMatura;
    private javax.swing.JTextField txtQtdCoagulante;
    private javax.swing.JTextField txtQuantFerm;
    private javax.swing.JTextField txtQuantidadeLeiteUtilizada;
    private javax.swing.JTextField txtReceitaQueijo;
    private javax.swing.JTextField txtTempPreMat;
    private javax.swing.JTextField txtTemperatura24;
    private javax.swing.JTextField txtTemperaturaCoagula;
    private javax.swing.JTextField txtTemperaturaPross;
    private javax.swing.JTextField txtTemperaturaSalga;
    private javax.swing.JTextField txtTempoCoagulacao;
    private javax.swing.JTextField txtTempoFermentacao;
    private javax.swing.JTextField txtTempoFermento;
    private javax.swing.JTextField txtTempoTratamento;
    private javax.swing.JTextField txtTipoFermento;
    // End of variables declaration//GEN-END:variables

    private Integer parseInteiro(String value) {

        if (Strings.isNullOrEmpty(value)) {
            return null;
        }
        return Integer.parseInt(value);
    }

    private Double parseDoubles(String value) {

        if (Strings.isNullOrEmpty(value)) {
            return null;
        }
        return Double.parseDouble(value);
    }

    private void consultar() {
        fq = cfq.consultar(Integer.parseInt(txtID.getText()));
    }
}
